### ISSUE TITLE
Schema for the API lookup enrichment

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/iglu-central#213]
Here's a starter instance:

```json
{
  "enabled": true,
  "parameters": {
    "inputs": {
      "user": [
        { "pojo": { "field": "user_id" } },
        { "json": {
            "schemaCriterion": "com.snowplowanalytics.snowplow/client_session/jsonschema/1-",
            "jsonPath": "$.userId"
          }
        },
        { "json": {
            "schemaCriterion": "com.acme/mobile_session/jsonschema/1-",
            "jsonPath": "$.user.id"
          }
        }
      ],
      "client": [
        { "pojo": { "field": "app_id" } }
      ]
    },
    "api": {
      "http": {
        "method": "GET",
        "uri": "http://api.acme.com/users/{{client}}/{{user}}",
        "authentication": {
          "http-basic": {
            "username": "xxx",
            "password": "yyy"
          }
        }
      }
    },
    "output": {
      "json": {
        "jsonPath": "*",
        "schema": "com.acme/user/jsonschema/1-0-0" 
      }
    },
    "cache": {
      "size": 3000,
      "ttl": 60
    }
  }
}
```

**Comment by alexanderdean** [comment]
@fblundun - thoughts on the above?

**Comment by fblundun** [comment]
Let me check if I understand what all the fields do.

This enrichment would check for the existence of a client_session context in the current event. If one is found, the enrichment would take the EnrichedEvent's user_id field and use it to make an http request to api.acme.com. The request would return a JSON which would be checked against the "com.acme/user/jsonschema/1-0-0"  schema. (I assume that "jsonPath: *" means use the top-level JSON rather than performing any extraction. Since the userId is just a string, does this mean that we are assuming that the API returns a single string instead of a JSON object?) This would be substituted into the userId field of the client_session context. Is that right?

**Comment by fblundun** [comment]
We would require special handling for APIs which return a single string like `abc` rather than `"abc"` since the former isn't actually a valid JSON.

**Comment by alexanderdean** [comment]
Thanks Fred - your interpretation has helped me clarify a few things! Broadly as you say, except:

1. The idea is that pojoFields and jsons are both places in the enriched event where the key can be found. I think I will restructure this so it is clearer
2. Good point that the returned JSON should be validated against the given schema

**Comment by alexanderdean** [comment]
Have made some updates inline above. @yalisassoon take a look!

**Comment by chuwy** [comment]
I guess, this can be closed?

**Comment by alexanderdean** [comment]
Duplicate of #276
