### ISSUE TITLE
Schema for a com.snowplowanalytics.snowplow/enriched_event

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/iglu-central#61]
This will be the documentation for the format we write into ElasticSearch.

**Comment by fblundun** [comment]
I will actually be changing this schema in the rebase - when I originally wrote it we didn't have the "unstruct_event_com_snowplowanalytics_snowplow_..." names for unstructured events and custom contexts. So this will be our first usage of the JSON schema `patternProperties` keyword, for fields which start "unstruct_event_" or "contexts_"

Maybe we should rename this schema to elasticsearch_enriched_event since the format is Elasticsearch-specific?

**Comment by alexanderdean** [comment]
Sounds good Fred - agree it should be ES specific...

**Comment by fblundun** [comment]
Maybe elasticsearch_stored_event to distinguish between enriching an event and making it suitable for a specific target?

**Comment by alexanderdean** [comment]
Hmm - I think _stored_ is implicit in the fact it starts with a storage target, elasticsearch_. I think let's stick with _enriched_ for now - I think there's an argument which says "enriched event" both over- and under-describes what a Snowplow {{enriched}} event is, but that's a debate for another day...
